- name: Discover K8s Pods
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Get pod info
      kubernetes.core.k8s_info:
        kind: Pod
        namespace: rhn-support-mtrujill-dev # apolamarasetti-dev
      register: pod_list

    - name: Build Dynamic Inventory
      ansible.builtin.add_host:
        name: "{{ item.metadata.name }}"
        ansible_host: "{{ item.status.podIP }}"
        ansible_connection: kubernetes.core.kubectl
        ansible_kubectl_namespace: "{{ item.metadata.namespace }}"
        groups:
          - discovered_pods
      loop: "{{ pod_list.resources }}"
      when: item.status.phase == 'Running'
      
    - name: Display Found Pods Summary
      ansible.builtin.pause:
        seconds: 1 # Brief pause so it stays in the log
        prompt: |
          -------------------------------------------------------
          DISCOVERED PODS IN: {{ pod_list.resources[0].metadata.namespace }}
          -------------------------------------------------------
          {% for pod in pod_list.resources %}
          - Name: {{ "%-50s" | format(pod.metadata.name) }} | IP: {{ pod.status.podIP }}
          {% endfor %}
          -------------------------------------------------------
